### ISSUE TITLE
emoji

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/changelog-test#10]
This one seems like its broken on my old-as-the-glacier macos
![Screen Shot 2019-12-23 at 15 24 58](https://user-images.githubusercontent.com/35242872/71363141-7831ae80-2598-11ea-8e99-be46c685aca0.png)

**Comment by jbolda** [comment]
Hmm, it must be an older emoji set. Have a better one to use?

**Comment by nothingismagick** [comment]
🔧
